using System.Text.Json.Serialization;

namespace WATIApi.Webhooks {
    //https://docs.wati.io/reference/template-message-sent
    /// <summary>Select `Template Message Sent v2` event type</summary>
    public class TemplateMessageSent : IWATIEventWithMessageID {
        /// <summary>
        /// Event type, here "templateMessageSent_v2" indicates a template message has been sent (version 2)
        /// </summary>
        [JsonPropertyName("eventType")]
        public string? EventType { get; set; }
        /// <summary>
        /// Local message identifier used by the client for tracking and idempotency
        /// </summary>
        [JsonPropertyName("localMessageId")]
        public string? LocalMessageID { get; set; }
        /// <summary>
        /// Unique identifier for the message
        /// </summary>
        [JsonPropertyName("id")]
        public string? ID { get; set; }
        /// <summary>
        /// Message ID generated by the WhatsApp platform
        /// </summary>
        [JsonPropertyName("whatsappMessageId")]
        public string? WhatsAppMessageID { get; set; }
        /// <summary>
        /// Unique identifier for the template used to send this message
        /// </summary>
        [JsonPropertyName("templateId")]
        public string? TemplateID { get; set; }
        /// <summary>
        /// Name of the template used for sending the message
        /// </summary>
        [JsonPropertyName("templateName")]
        public string? TemplateName { get; set; }
        /// <summary>
        /// Timestamp when the message was created (ISO 8601 format)
        /// </summary>
        [JsonPropertyName("created")]
        public string? Created { get; set; }
        /// <summary>
        /// Unique identifier for the conversation, used to associate all messages within the same conversation
        /// </summary>
        [JsonPropertyName("conversationId")]
        public string? ConversationID { get; set; }
        /// <summary>
        /// Ticket ID used for ticket management in customer service systems
        /// </summary>
        [JsonPropertyName("ticketId")]
        public string? TicketID { get; set; }
        /// <summary>
        /// Text content of the template message
        /// </summary>
        [JsonPropertyName("text")]
        public string? Text { get; set; }
        /// <summary>
        /// Email address of the operator/customer service representative who sent the message
        /// </summary>
        [JsonPropertyName("operatorEmail")]
        public string? OperatorEmail { get; set; }
        /// <summary>
        /// WhatsApp ID, typically the complete phone number with country code
        /// </summary>
        [JsonPropertyName("waId")]
        public string? WA_ID { get; set; }
        /// <summary>
        /// Message type, supported values include: "image", "text", "document", "location", "voice", "audio", "button", "interactive", "reaction", "video", "sticker", "contacts", "order", "catalog", "media_placeholder", "template"
        /// </summary>
        [JsonPropertyName("type")]
        public string? Type { get; set; }
        /// <summary>
        /// Message status string, here "SENT" indicates the message has been sent successfully
        /// </summary>
        [JsonPropertyName("statusString")]
        public string? StatusString { get; set; }
        /// <summary>
        /// Source from which the message was sent, "WEB" indicates it was sent from the web interface
        /// </summary>
        [JsonPropertyName("sourceType")]
        public string? SourceType { get; set; }
        /// <summary>
        /// Link associated with the template header, null if no header link is present
        /// </summary>
        [JsonPropertyName("headerLink")]
        public string? HeaderLink { get; set; }
        /// <summary>
        /// Type of header in the template (e.g., "text", "image", "video"), null if no header is present
        /// </summary>
        [JsonPropertyName("headerType")]
        public string? HeaderType { get; set; }
        /// <summary>
        /// Identifier of the channel through which the message was sent, null if using default channel
        /// </summary>
        [JsonPropertyName("channelId")]
        public string? ChannelID { get; set; }
        /// <summary>
        /// Phone number of the channel from which the message was sent
        /// </summary>
        [JsonPropertyName("channelPhoneNumber")]
        public string? ChannelPhoneNumber { get; set; }
    }
}
